### ISSUE TITLE
what is the root password?

### ISSUE THREAD

**Issue by scil** [iainmckay/docker-phpstorm#1]
I have to install some php ext, and need root . But i can't find root password. Could u tell me?

**Comment by scil** [comment]
now log in as root by ' -u root'

**Comment by iainmckay** [comment]
There isn't a root password set. If you need to add extensions I'd either fork and customize the Dockerfile or let me know what they are and I can perhaps include them in my image. I only added the extensions I needed at the time I built this.

**Comment by scil** [comment]
Thank you!
I use ext Swoole https://github.com/swoole/swoole-src  , which is not popular.

**Comment by iainmckay** [comment]
Are you sure you need this installed in the editor? Does phpstorm use it via an extension? It looks to me like this should be part of your runtime, not the editor.

Could you clarify?

**Comment by scil** [comment]
php ext, not phpstorm.  Thank you!
