### ISSUE TITLE
Permission denied for update

### ISSUE THREAD

**Issue by mykiwi** [iainmckay/docker-phpstorm#2]
I can't get the update 9.0.1, this message appear:

> PhpStorm does not have write access to /opt/phpstorm. Please run it by a privileged user to update.

**Comment by iainmckay** [comment]
Yep, the app itself doesn't have access to update itself. You probably don't want this to happen inside the container as you'd lose the update when you restarted the editor.

I've updated the Dockerfile to install the latest 9.0.2 release, it's building now and will be available in the next 20-30 minutes from dockerhub.
